### PR TITLE
Update sockjs-client-node to support node >= 4.x.x

### PR DESCRIPTION
**Pull request by fatelei**

### CODE REVIEW

**Comment by fatelei** [comment]
@lpinca Hi，there is pr, :)

**Comment by jcrugzz** [comment]
@fatelei this would be a `1.0.0` change since this is breaking. Seems reasonable though

**Comment by fatelei** [comment]
@jcrugzz ok :)

**Comment by lpinca** [comment]
@fatelei why are you still using this? The official [`sockjs-client`](https://github.com/sockjs/sockjs-client) now works also on node.

**Comment by fatelei** [comment]
I find `sockjs-client` can't work on node.

**Comment by lpinca** [comment]
I'm going to merge this and publish a new version adding a deprecation warning.
You should definitely switch to the official `sockjs-client`, it works on node since version `1.0.0`.

**Pull request merged**
